---
- name: "AWS : credentials : ensure target directory exists."
  file:
    path: "{{ controlhost_aws_credentials_path | dirname }}"
    owner: "{{ controlhost_user }}"
    group: "{{ controlhost_group }}"
    mode: 0700
    state: directory

- name: "AWS : credentials : copy aws credentials to controlhost."
  copy:
    src: "{{ controlhost_aws_credentials_src }}"
    dest: "{{ controlhost_aws_credentials_path }}"
    owner: "{{ controlhost_user }}"
    group: "{{ controlhost_group }}"
    mode: 0600
