---
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
env:
  # run against latest version
  - ANSIBLE_VERSION=latest
  # run against minimal required version
  - ANSIBLE_VERSION=2.4.*

# Use the new container infrastructure
sudo: false

# Install pip
addons:
  apt:
    packages:
    - python-pip
    - python3-pip

install:
  # Install ansible and dependencies
  - PIP=$(which pip3 || which pip); if [ "$ANSIBLE_VERSION" = "latest" ]; then "$PIP" install ansible ansible-lint --upgrade; else "$PIP" install ansible=="$ANSIBLE_VERSION" ansible-lint --upgrade; fi

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=./tests/requirements/:../' >ansible.cfg

script:
  # Install requirements
  - ansible-galaxy install -r tests/requirements.yml -p ./tests/requirements

  # Run ansible-lint
  - ansible-lint .

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/