- name: Include OS family specific variables.
  include_vars: "family_{{ ansible_os_family }}.yml"

- name: Install os packages
  include_tasks: "packages/os.yml"
  tags:
    - os-packages
    - packages
  when: controlhost_packages_os_enabled

- name: Install pip packages
  include_tasks: packages/pip.yml
  tags:
    - pip-packages
    - packages
  when: controlhost_packages_pip_enabled

- name: Setup ansible
  include_tasks: ansible/setup.yml
  tags:
  - ansible

- name: Setup AWS
  include_tasks: aws/setup.yml
  tags:
  - aws

- name: Setup maven
  include_tasks: maven/setup.yml
  tags:
    - maven

- name: Setup nodejs
  include_tasks: nodejs/setup.yml
  tags:
  - nodejs

- name: Setup environment
  include_tasks: env/setup.yml
  tags:
    - env
