- name: Configure default editor
  blockinfile:
    path: "{{ controlhost_bashrc }}"
    block: "export EDITOR={{ controlhost_bashrc_editor }}"
    marker: "# {mark} editor ANSIBLE MANAGED BLOCK"
  when: controlhost_default_editor is defined

- name: "Set environment variable ANSIBLE_VAULT_PASSWORD_FILE to ansible vault pass"
  block:
  - name: Configure ansible vault environment variable
    blockinfile:
      path: "{{ controlhost_bashrc }}"
      block: "export ANSIBLE_VAULT_PASSWORD_FILE={{ controlhost_vault_pass_path }}"
      marker: "# {mark} ansible-vault ANSIBLE MANAGED BLOCK"

  - name: Print hint for sourcing of .bash_profile
    debug:
      msg:
        - Make sure to execute 'source ~/.bashrc' to ensure that environment variable 'ANSIBLE_VAULT_PASSWORD_FILE' is present

  when: controlhost_vault_pass_path is defined
