---
- name: "Maven : sanitize item.id"
  set_fact:
    _item_id: "{{ item.id | regex_replace('[^a-zA-Z0-9_]','_') }}"

- name: "Maven : encrypt_password : Encrpyt maven server password when maven master password is defined."
  block:
    - name: "Maven : encrypt_password : encrypt maven server password"
      command: "mvn --encrypt-password {{ item.password }}"
      register: _maven_encrypted_server_password
      become_user: "{{ controlhost_user }}"
      become: yes
      no_log: true

    - name: "Maven : encrypt_password : set password fact for server with id : {{ item.id }}"
      set_fact:
        {"_maven_encrypted_server_password_{{ _item_id }}":"{{ _maven_encrypted_server_password.stdout }}"}
      no_log: true
  when: controlhost_maven_master_password is defined

- name: "Maven : encrypt_password : Set unencrypted maven server password when  maven master password is not defined."
  set_fact:
    {"_maven_encrypted_server_password_{{ _item_id }}":"{{ item.password }}"}
  no_log: true
  when: controlhost_maven_master_password is not defined
