- name: Define controlhost_packages.
  set_fact:
    controlhost_packages_os: "{{ __controlhost_packages_os }}"
  when: controlhost_packages_os is not defined

- name: "packages : os : Install required packages."
  package:
    name: "{{ controlhost_packages_os }}"
    state: present
  register: _controlhost_packages_os_result
  until: _controlhost_packages_os_result | success
  retries: 3
