- name: "packages : pip : Upgrade pip"
  pip:
    name: "pip"
    state: latest
  when: controlhost_packages_pip_upgrade
  tags:
    - skip_ansible_lint

- name: "packages : pip : Install required PIP packages."
  pip:
    name: "{{ controlhost_packages_pip }}"
    state: present
  register: _controlhost_packages_pip_result
  until: _controlhost_packages_pip_result is success
  retries: 3