- name: "packages : pip : Upgrade pip"
  pip:
    name: "pip"
    state: latest
  when: controlhost_packages_pip_upgrade
  tags:
    - skip_ansible_lint

- name: "packages : pip : Install required PIP packages."
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ controlhost_packages_pip }}"
